### ISSUE TITLE
Autogenerated files code and extra/ role

### ISSUE THREAD

**Issue by techtonik** [FarGroup/www#2]
https://github.com/FarGroup/www/blob/4cb75bb19d93119126d2d9c608d4023d1c5ebea4/README.md#L3

Not clear how autogeneration works and what is the connection between website sources and `extra/` directory at the top.

**Comment by alabuzhev** [comment]
> Not clear how autogeneration works

https://github.com/FarGroup/FarManager/blob/master/misc/nightly/publish.sh#L25

> what is the connection between website sources and extra/ directory at the top

extra/ contains some maintenance scripts.
